#!/usr/bin/env ruby

require 'cinch'

class Seen < Struct.new(:who, :where, :what, :time)
  def to_s
    "[#{time.asctime}] #{who} was seen in #{where} saying #{what}"
  end
end

bot = Cinch::Bot.new do
  configure do |c|
    c.server = 'irc.freenode.org'
    c.nick = 'pidroid-bot'
    c.realname = 'pidroid'
    c.user = 'pidroid'
    c.channels = [ '#pidroid', '#pidroid-dev' ]

    @users = {}
  end

  on :message, 'hello' do |m|
    m.reply "Hello, #{m.user.nick}"
  end

  on :channel do |m|
    @users[m.user.nick] = Seen.new(m.user.nick, m.channel, m.message, Time.new)
  end

  on :channel, /^\s*pidroid-bot[:,](.+)/ do |m, nick|
    m.reply "That's me!"
  end
end

bot.start
