#!/usr/bin/env ruby

require 'cinch'

bot = Cinch::Bot.new do
  configure do |c|
    c.server = 'irc.freenode.org'
    c.nick = 'pidroid-bot'
    c.realname = 'pidroid'
    c.user = 'pidroid'
    c.channels = [ '#pidroid', '#pidroid-dev' ]
  end

  on :message, 'hello' do |m|
    m.reply "Hello, #{m.user.nick}"
  end

  on :channel, /^\s*pidroid-bot[:,](.+)/ do |m, nick|
    m.reply "That's me!"
  end
end

bot.start
